version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building the application..."
      - ./mvnw clean package -DskipTests
artifacts:
  files:
    - target/*.jar
